<?php
$lang=array(

    "un" =>"Hours of work",
    "deux" =>"Mon - Fri, 8:30 - 16:30",
    "call"=>"Call Us",
    "call2"=>"+216 31401447",
    "email"=>"Email Us",
    "email2"=>"ska.fluides@gmail.com",
    "home"=>"Home",
    "about"=>"about",
    "service"=>"service",
    "service2"=>"Our services",
    "service3"=>"We Offer Services    ",

    "s1"=>"Air conditioning",
    "s1i"=> "
    we offer you with the best types of regular and central air conditioning, We work through a team with the most recent and very experienced equipment:
    Central air conditioning for large installations using high airflows
    And residential air conditioning using conventional air conditioners",    
    "s2"=>"Heating",
    "s2i"=>"
    We offer different types of heating according to technical requirements: central heating / floor heating / domestic heating
  ",
    
    "s3"=>"sanitary Plumbing",
    "s6"=>"Fire-fighting",
    "s7"=>"Central extinguishing system (cocked fire valve)",
"s8"=>"Water spray extinguishing system sprinkler",
"s7i"=>"RIAs are first aid equipment.
Directly connected to a water source, they have the advantage of high power and long duration of action. They are located as close as possible to the risks to be protected.",
"s8i"=>"A fixed automatic water extinguishing installation, also called a sprinkler, is an extinguishing device that operates alone in the event of excessive heat in a room or site to be protected during a fire. This system is networked above the area to be protected.",
    "s3i"=>"
    We provide all plumbing services, sanitary work and all plumbing needs, whether it is installing or maintaining drinking water pipes and sewer lines in homes, factories, offices and various other facilities",   
    "s4"=>"swimming pool",
    "s4i"=>"Our installation teams perfectly master the installation and maintenance procedures of swimming pools",
"s6i"=>"We provide you with a range of fire fighting and alarm systems, and we work with you to find the system that meets your needs.",
    "s5"=>"spa",
    "s5i"=>"A spa or hydrotherapy center is an establishment of beauty care or fitness using mineral hydrotherapy and sea water.",
    "lien"=>"links",
    "val"=>"our values",
    "part2"=>"Suppliers",
    "news"=>"STAFF MEMBERS",
    "part3"=>"Building Design",
    "project"=>"projects",
    "part"=>"PARTNERS",
    "contact"=>"contact",
    "contact2"=>"Contact-us",
    "1"=>"ENJOY YOUR SEASON WITH ",
    "2"=>"You can count on us to keep you cool all summer and warm in winter",
    "b"=>"administrative members ",
    "b2"=>"City ben smina yassminet , new city Ben Arous Est, 2096",
    "t"=>"Fhones ",
    "t2"=>"FIXE : 31401447",
    "t3"=>"FAX :  32401447",
    "t4"=>"GSM : 53084671 ",
    "t5"=>" GSM2 : 25661207 ",
     "x"=>"Innovation / tailor-made     ",
     "x2"=>"Your technical partner for the development of your fluid projects"  ,
     "forum1"=>"Get In Touch",
     "forum2"=>"For Any Query"  ,
     "location"=>"Our Location",
     "phone"=>"Phone",
     "mail"=>"Email",
     "name"=>"Your Name",
     "subj"=>"Subject",
     "msg"=>"Message",
     "env"=>"Send Message",
     "val"=>"Type the number",
     "trad"=>"Website translation",
     "trad2"=>  "choose a language ",
     "trad3"=> "Translate",
     "wel"=> "WELCOME TO SKA FLUIDES",
     "soc"=> "SKA Fluides Company ",
     "se"=>"We provide the best services",
     "def"=>"
     Tunisian company, founded in 2010 Located in Tunis, Ben Arous, with recognized experience in the field of industrial services, with a capital of 80,000 Tunisian dinars to carry out air conditioning, heating, swimming pool, sanitary plumbing and spa. It provides various services in this field with high quality solutions for each of its clients through innovative personal project solutions.",     "of"=>"PROVIDING PERSONALIZED AND HIGH QUALITY SERVICES     ",
     "of2"=>"We can manage your dream project, contact us for more details",
     "ska"=>" Innovation",
     "sk1"=>"Tailor-made",
     "sk2"=>"Humanity",
"ska2"=>"Since its creation, the ska fluides company has been 100% committed to respecting the values that have made its strength. They are expressed today through our teams of experts and enthusiasts.",
"ska3"=>"The meteo is what we expect, the weather is what we get.",
"par"=>"ska fluides providers",
"msgs"=>"Your contact information is received successfully .",
"msgs2"=>"your Email address is not valid .",
"msgs3"=>"You have not completed all the champs. Your request has not been sent.",
"p1"=>"With our partners, we offer professional services with a clear and responsible commitment. ",
"ps"=>"WE BUILD PARTNERSHIPS",
"ps2"=>"A TEAM OF PROFESSIONALS",

"pr"=>"ALL",
"pr1"=>" MANOUBA COMPLEX",
"pr2"=>"MECAPROTEC",
"pr3"=>"VILLAS",
"pr4"=>"BUILDINGS",
"pr5"=>"SPORTS HALL",
"v"=>"view all projects",
"v2"=>"view all partners",
"tt" => "projects carried out",
"tt2" => "current projects",
"tt3"=>"LIST OF OUR CURRENT PROJECTS",
"pe2" => "hwereb prison",
"pe3" => "silaina foyer",
"pe4" => "cap gammarth",
"pe5" => "splt lake",
"pe9"=>"Siliana municipal swimming pool",
"pe10"=>"manouba municipal swimming pool",
"pe11"=>"Renovation of the Tunis Court of First Instance",
"pe12"=>"Multidisciplinary room Ben Guerdane",
"pe13"=>"Exemplary institute El Kef",
"pe6" => "pilot high school and beja college",
"pe7" => "house for people and house for the elderly",
"pe8" => "kasserine regional hospital",
"defre0" => "What is an industrial fluid?",
"defre"=>"A fluid, liquid or gas, refers to any substance that can flow. Compressed air, steam or ice water are fluids that can have industrial applications. During a winery, pressure equipment or industrial piping project with thermal insulation, it is necessary to carry out a study of the fluid processes.

They are present in all areas, including domestic housing with the wall-mounted boiler, electric water heater, refrigeration, storm water delivery system, etc. The management of these fluids requires a set of equipment such as valves. industrial for example: valve, non-return valve, filter, valve, expansion compensator, brass fittings ... For gas, it is the solenoid valve, the pressure reducer, the servomotor and the pressure switch which causes the start of a air compressor or water pump. Tubes and pipes fitted with clamps are used for transporting fluids, etc.",
"defre3"=>"our capital",
"defre1"=>"Where do we work?",
"defre2" => "We are at your disposal throughout the territory of the Republic",
"f" => "beja prison and high school ",




);
?>