<?php
$lang=array(

    "un" =>"Horaires de travail",
    "deux" =>"Lun - Vend, 8:30 - 16:30",
    "call"=>"Appelez-nous",
    "call2"=>"+216 31401447",
    "email"=>"Envoyez-nous un email",
    "email2"=>"ska.fluides@gmail.com",
    "home"=>"Accueil",
    "about"=>"A propos",
    "service"=>"services",
    "service2"=>"Nos services",
    "service3"=>"Nous offrons des services",
    "s1"=>"Climatisation",

    "s1i"=>"
    nous vous fournissons les meilleurs types de climatisation régulière et centrale, Nous travaillons au travers d'une équipe dotée des équipements les plus récents et très expérimentés  :
    Climatisation centrale pour les installations de grande taille utilisant des débits d'air élevés
    Et la climatisation résidentielle utilisant des climatiseurs conventionnels",
        "s2"=>"Chauffage",
        "s7"=>"Système central d'extinction (Robinet d'incendie armé)",
        "s8"=>"Système d'extinction par pulvérisation d'eau (SPRINKLER)",
        "s7i"=>"Les RIA sont des équipements de première intervention.
        Directement branchés sur une source d’eau, ils présentent l’avantage d’une grande puissance et d’une durée d’action importante. Ils sont implantés le plus près possible des risques à protéger.",
        "s8i"=>"Une installation fixe d'extinction automatique à eau nommée aussi sprinkler est un appareil d'extinction fonctionnant seul en cas de chaleur excessive dans un local ou un site à protéger lors d’un incendie. Ce système est mis en réseau au-dessus de la zone à protéger.",
        "s6i"=>"Nous mettons à votre disposition une gamme de systèmes de lutte contre l'incendie et d'alarme, et nous travaillons avec vous pour trouver le système qui répond à vos besoins",
    "s2i"=>"
    Nous vous proposons des différents types de chauffage selon les exigences techniques : chauffage central / chauffage parlesol / chauffage domestique    ",
    "s3"=>"plomberie sanitaire",
    "s3i"=>"  Nous fournissons tous les services de plomberie, les travaux sanitaires et tous les besoins de plomberie, qu'il s'agisse d'installer ou d'entretenir des conduites d'eau potable et des conduites d'égout dans les maisons, les usines, les bureaux et diverses autres installations",    "s4"=>"piscine",
    "s4i"=>"Nos équipes de pose maitrisent parfaitement les procédures d'installation et maintenance des piscines",
    "s5"=>"spa",
    "s5i"=>"Un spa ou centre d'hydrothérapie est un établissement de soins esthétiques ou de remise en forme à l'aide de l'hydrothérapie  minérale et l'eau de mer.. ",
"lien"=>"liens",
    "news"=>"Notre equipe",
    "project"=>"Nos projets",
    "s6"=>"lutte contre incendie",
    "part"=>"partenaires",
    "part2"=>"Fournisseurs",
    "part3"=>" Bureaux D'études ",
    "contact"=>"Contact",
    "contact2"=>"Contactez-nous",
    "1"=>"Profitez de votre saison Avec ",
    "2"=>"Vous pouvez compter sur nous pour vous garder au frais tout l'été et au chaud en hiver    ",
    "b"=>"membres administratifs ",
    "b2"=>"Cité Ben smina yassminet , nouvelle ville Ben Arous Est, 2096 ",
    "t"=>"Téléphones ",
    "t2"=>"FIXE : 31401447   ",
    "t3"=>"    FAX :  32401447 ",
    "t4"=>"GSM : 53084671 ",
    "t5"=>" GSM2 : 25661207 ",
     "x"=>"Innovation / sur-mesure     ",
     "x2"=>"Votre partenaire technique pour le développement de vos projets fluides  "  ,
     "forum1"=>"N'HÉSITEZ PAS À PRENDRE CONTACT AVEC NOTRE ÉQUIPE",
     "forum2"=>"Nos conseillers se tiennent à votre disposition"  ,
     "location"=>"Notre Adresse",
     "phone"=>"téléphone",
     "mail"=>"Email",
     "name"=>"Votre Nom",
     "subj"=>"Sujet",
     "msg"=>"Votre Message",
     "env"=>"Envoyer",
"val"=>"Tapez le numéro",
"trad"=>"Traduction de site",
"trad2"=>  " choisir une langue",
"trad3"=> "Traduire",
"wel"=> "BIENVENUE CHEZ SKA FLUIDES",
"soc"=> "Société SKA Fluides ",
"se"=>"Nous fournissons les meilleurs services industriels ",
"def"=>"
Société tunisienne, fondée en 2010 Localisée  à Tunis, Ben Arous, avec une expérience reconnue dans le domaine des services industriels, au capital de 80 000 dinars tunisiens pour réaliser des travaux de climatisation, chauffage , psicine, plomberie sanitaire et spa en tous locaux. Elle fournit divers services dans ce domaine avec des solutions de haute qualité pour chacun de ses clients à travers des solutions de projets personnels innovants ","of"=>" OFFRIR DES SERVICES professionnels ET DE HAUTE QUALITÉ ",
"of2"=>"Nous sommes professionnels , Pour votre projet de rêve contactez-nous pour plus de détails .",
"ska"=>" Innovation ",
"sk1"=>" Sur-mesure ",
 "sk2"=>"Humaine",
"ska2"=>"Depuis sa création, la société ska fluides s’engage à 100% dans le respect des valeurs qui ont fait sa force. Elles s’expriment, aujourd’hui, à travers nos équipes d’experts et passionnés.",
"ska3"=>"La météo c'est ce à quoi on s'attend, le climat c'est ce que nous obtenons.",
"par"=>"les fournisseurs de ska fluides",
"msgs"=>"Votre message a été reçu avec succès",
"msgs2"=>" Votre adresse e-mail n'est pas valide",
"msgs3"=>"Vous n'avez pas rempli tous les champs. Votre demande n'a pas été envoyée.",
"p1"=>"Avec nos partenaires, nous offrons des services professionnels avec un engagement clair et responsable.",
"val"=>"Nos valeurs",
"ps"=>"Nous construisons des partenaires",
"ps2"=>"UNE ÉQUIPE DE PROFESSIONNELS",
"pr"=>"TOUT",
"v"=>"voir tous les projets",
"v2"=>"voir tous les partenaires",
"pr1"=>"COMPLEXE MANOUBA",
"pr2"=>"MECAPROTEC",
"pr3"=>"VILLAS",
"pr4"=>"IMMEUBLES",
"pr5"=>"SALLE DE SPORT",

"tt"=>"projets realisés",
"tt2"=>"projets en-cours",
"tt3"=>"liste de nos projets en-cours",
"pe2"=>"prison hwereb",
"pe3"=>"foyer silaina",
"pe4"=>"cap gammarth",
"pe5"=>"splt lac",
"pe6"=>"lycée pilote et collége  beja ",
"pe7"=>"maison de oersonnes et maison des personnes agées ",
"pe8"=>"hôpital régional kasserine ",
"pe9"=>"Piscine municipale de Siliana",
"pe10"=>"Piscine municipale de manouba",
"pe11"=>"Renovation du Tribunal de Première Instance de Tunis",
"pe12"=>"Salle multidisciplinaire Ben Guerdane",
"pe13"=>"Institut exemplaire à El Kef",
"defre0"=>"Qu’est-ce qu’un fluide industriel ?",
"defre3"=>"Notre capital",
"f"=>"prison et lycée pilote beja",
"defre1"=>"Où travaillons-nous ?",
"defre"=>"Un fluide, liquide ou gazeux, désigne toute substance qui peut couler. L’air comprimé, la vapeur ou l’eau glacée sont des fluides qui peuvent avoir des applications industrielles. Lors d’un projet de cuverie, d’équipement sous pression ou de tuyauterie industrielle avec calorifugeage, il  est nécessaire de réaliser une étude des procédés fluides.

Ils sont présents dans tous les domaines, y compris l’habitat domestique avec la chaudière murale, le chauffe-eau électrique, la réfrigération, le système de refoulement des eaux pluviales… La gestion de ces fluides nécessite un ensemble d’équipements comme en robinetterie industrielle par exemple : vanne, clapet anti-retour, filtre, soupape, compensateur de dilatation, raccords laiton… Pour le gaz, c’est l’électrovanne, le réducteur de pression, le servomoteur et le pressostat qui provoque le démarrage d’un compresseur d’air ou d’une pompe à eau. Les tubes et tuyaux équipés de colliers de serrage servent au transport des fluides, etc.",
"defre2" => "Nous sommes à votre disposition sur tout le territoire de la République",





);
?>